-- ============================================
-- AGENT MEMORY: Personal + Collective Learning
-- ============================================
-- Each agent has their own memory log of past decisions and outcomes.
-- They also see the collective decision log to understand what the group decided.

-- ============================================
-- AGENT MEMORY: Personal decision history
-- ============================================
CREATE TABLE agent_memory (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    agent_name TEXT NOT NULL,  -- bighead, gavin, gilfoyle, dinesh, laurie, monica, erlich, jared, richard, russ
    run_number INTEGER NOT NULL,
    run_id UUID REFERENCES runs(id),

    -- What they decided
    decision_type TEXT NOT NULL,  -- 'analysis', 'proposal', 'critique', 'approval', 'rejection', etc.
    decision_summary TEXT NOT NULL,  -- Brief summary of what they said
    decision_details JSONB,  -- Full output for reference
    confidence DECIMAL(3,2),  -- How confident were they (0-1)

    -- What happened after (filled in by next run)
    outcome TEXT,  -- 'implemented', 'rejected', 'modified', 'pending'
    outcome_details JSONB,

    -- Metrics at decision time vs after
    conversion_at_decision DECIMAL(5,2),
    conversion_after DECIMAL(5,2),  -- Filled in 24h later

    -- Did their call turn out to be right?
    was_correct BOOLEAN,  -- Filled in after we have outcome data
    correctness_reasoning TEXT,

    -- Self-reflection (generated by the agent in next run)
    lessons_learned TEXT,
    would_decide_differently BOOLEAN,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_memory_agent ON agent_memory(agent_name);
CREATE INDEX idx_agent_memory_run ON agent_memory(run_number);
CREATE INDEX idx_agent_memory_agent_recent ON agent_memory(agent_name, run_number DESC);

-- ============================================
-- COLLECTIVE LOG: Group decisions visible to all
-- ============================================
CREATE TABLE collective_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    run_number INTEGER NOT NULL,
    run_id UUID REFERENCES runs(id),

    -- Summary of the run
    run_summary TEXT NOT NULL,

    -- Key decisions
    proposal_summary TEXT,  -- What Gavin proposed
    critique_summary TEXT,  -- What Gilfoyle said
    final_decision TEXT,    -- What Laurie decided

    -- Who agreed/disagreed
    agent_positions JSONB,  -- { "gavin": "proposed X", "gilfoyle": "rejected", "dinesh": "concerned about Y" }

    -- Outcome
    changes_made JSONB,
    spend_amount DECIMAL(10,2),

    -- Results (filled in after)
    conversion_before DECIMAL(5,2),
    conversion_after DECIMAL(5,2),
    was_successful BOOLEAN,  -- Did conversion improve?

    -- Collective lessons
    what_worked TEXT,
    what_didnt_work TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_collective_log_run ON collective_log(run_number DESC);

-- ============================================
-- View: Agent's personal track record
-- ============================================
CREATE OR REPLACE VIEW agent_track_record AS
SELECT
    agent_name,
    COUNT(*) as total_decisions,
    COUNT(*) FILTER (WHERE was_correct = true) as correct_decisions,
    COUNT(*) FILTER (WHERE was_correct = false) as incorrect_decisions,
    COUNT(*) FILTER (WHERE was_correct IS NULL) as pending_decisions,
    ROUND(
        COUNT(*) FILTER (WHERE was_correct = true)::numeric /
        NULLIF(COUNT(*) FILTER (WHERE was_correct IS NOT NULL), 0) * 100,
        1
    ) as accuracy_pct,
    AVG(confidence) FILTER (WHERE was_correct = true) as avg_confidence_when_right,
    AVG(confidence) FILTER (WHERE was_correct = false) as avg_confidence_when_wrong
FROM agent_memory
GROUP BY agent_name;

-- ============================================
-- View: Recent collective decisions
-- ============================================
CREATE OR REPLACE VIEW recent_collective_decisions AS
SELECT
    run_number,
    run_summary,
    final_decision,
    agent_positions,
    conversion_before,
    conversion_after,
    was_successful,
    what_worked,
    what_didnt_work,
    created_at
FROM collective_log
ORDER BY run_number DESC
LIMIT 20;

-- ============================================
-- View: Agent learning trends
-- ============================================
CREATE OR REPLACE VIEW agent_learning_trends AS
SELECT
    agent_name,
    run_number,
    decision_summary,
    was_correct,
    lessons_learned,
    -- Running accuracy over last 10 decisions
    AVG(CASE WHEN was_correct THEN 1.0 ELSE 0.0 END)
        OVER (PARTITION BY agent_name ORDER BY run_number ROWS BETWEEN 9 PRECEDING AND CURRENT ROW)
        as rolling_accuracy
FROM agent_memory
WHERE was_correct IS NOT NULL
ORDER BY agent_name, run_number DESC;
